### ISSUE TITLE
Default modbus2mqtt.yaml

### ISSUE THREAD

**Issue by nikito7** [modbus2mqtt/server#11]
How/where to create modbus2mqtt.yaml?

9/4/2024 2:12:39 PM notice config configuration file  not found /data/local/modbus2mqtt.yaml

**Comment by nikito7** [comment]
mqtt discovery not working

-----------------------------------------------------------
 Add-on: Modbus <=> MQTT
 Service converts RTU and TCP Modbus to MQTT from other
-----------------------------------------------------------
 Add-on version: 0.16.4
 You are running the latest version of this add-on.
 System: Home Assistant OS 13.1  (amd64 / qemux86-64)
 Home Assistant Core: 2024.8.3
 Home Assistant Supervisor: 2024.08.0
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
s6-rc: info: service base-addon-banner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service base-addon-log-level: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service base-addon-log-level successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
9/4/2024 2:18:02 PM notice config configuration file  not found /data/local/modbus2mqtt.yaml
9/4/2024 2:18:03 PM notice modbus2mqtt module dir: /usr/app/node_modules/@modbus2mqtt/angular/dist/browser/en-US/index.html
9/4/2024 2:18:03 PM notice modbus2mqtt http root : /usr/app/node_modules/@modbus2mqtt/angular/dist/browser
9/4/2024 2:18:03 PM notice bus Already up to date.
9/4/2024 2:18:03 PM notice bus 
9/4/2024 2:18:04 PM notice config specifications directory not found /data/contributed/specifications
9/4/2024 2:18:04 PM notice config specifications directory not found /data/local/specifications
9/4/2024 2:18:04 PM notice HttpServerBase Hassio authentication successful
9/4/2024 2:18:04 PM notice modbus2mqtt modbus2mqtt listening on  37e92509-modbus2mqtt: 3000
9/4/2024 2:18:04 PM ERR! mqttdiscover poll: MQTT client is not connected
/usr/app/node_modules/@modbus2mqtt/server/dist/mqttdiscover.js:424
            throw new Error('poll: MQTT client is not connected');
                  ^

Error: poll: MQTT client is not connected
    at MqttDiscover.getMqttClient (/usr/app/node_modules/@modbus2mqtt/server/dist/mqttdiscover.js:424:19)
    at /usr/app/node_modules/@modbus2mqtt/server/dist/mqttdiscover.js:518:46
    at Array.forEach (<anonymous>)
    at /usr/app/node_modules/@modbus2mqtt/server/dist/mqttdiscover.js:517:41
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v18.20.3
npm notice
npm notice New patch version of npm available! 10.8.2 -> 10.8.3
npm notice Changelog: https://github.com/npm/cli/releases/tag/v10.8.3
npm notice To update run: npm install -g npm@10.8.3
npm notice
[14:18:04] INFO: Service  exited with code 1 (by signal 0)
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service modbus2mqtt: stopping
s6-rc: info: service modbus2mqtt successfully stopped
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service base-addon-log-level: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service base-addon-log-level successfully stopped
s6-rc: info: service base-addon-banner: stopping
s6-rc: info: service base-addon-banner successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
s6-rc: info: service modbus2mqtt: starting
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service modbus2mqtt successfully started
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service base-addon-banner: starting

-----------------------------------------------------------
 Add-on: Modbus <=> MQTT
 Service converts RTU and TCP Modbus to MQTT from other
-----------------------------------------------------------
 Add-on version: 0.16.4
 You are running the latest version of this add-on.
 System: Home Assistant OS 13.1  (amd64 / qemux86-64)
 Home Assistant Core: 2024.8.3
 Home Assistant Supervisor: 2024.08.0
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
s6-rc: info: service base-addon-banner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service base-addon-log-level: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service base-addon-log-level successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
9/4/2024 2:38:25 PM notice config configuration file  not found /data/local/modbus2mqtt.yaml
9/4/2024 2:38:25 PM notice modbus2mqtt module dir: /usr/app/node_modules/@modbus2mqtt/angular/dist/browser/en-US/index.html
9/4/2024 2:38:25 PM notice modbus2mqtt http root : /usr/app/node_modules/@modbus2mqtt/angular/dist/browser
Cloning into '/data/public'...
9/4/2024 2:38:26 PM notice bus 
9/4/2024 2:38:27 PM notice config specifications directory not found /data/contributed/specifications
9/4/2024 2:38:27 PM notice config specifications directory not found /data/local/specifications
9/4/2024 2:38:27 PM notice HttpServerBase Hassio authentication successful
9/4/2024 2:38:27 PM notice modbus2mqtt modbus2mqtt listening on  37e92509-modbus2mqtt: 3000
9/4/2024 2:38:28 PM ERR! mqttdiscover poll: MQTT client is not connected
