### ISSUE TITLE
Unable to start modbus2mqtt on HA - error "MQTT client is not connected"

### ISSUE THREAD

**Issue by albgit** [modbus2mqtt/server#15]
Hi,
today I've updated to 0.16.6 and after doing some changes modbus2mqtt don't start anymore.
It was working fine before, except for one configuration: update interval at the slave submenu (default 1000 ms, I want an higher value). After that I deleted the slave, created a new one with the same address (3) and then applied the specification that I saved.
Here the log:

-----------------------------------------------------------

 Add-on: Modbus <=> MQTT
 Service converts RTU and TCP Modbus to MQTT from other
-----------------------------------------------------------
 Add-on version: 0.16.6
 You are running the latest version of this add-on.
 System: Home Assistant OS 13.1  (amd64 / generic-x86-64)
 Home Assistant Core: 2024.9.1
 Home Assistant Supervisor: 2024.09.1
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
s6-rc: info: service base-addon-banner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service base-addon-log-level: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service base-addon-log-level successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
9/16/2024 11:39:14 PM notice modbus2mqtt module dir: /usr/app/node_modules/@modbus2mqtt/angular/dist/browser/en-US/index.html
9/16/2024 11:39:14 PM notice modbus2mqtt http root : /usr/app/node_modules/@modbus2mqtt/angular/dist/browser
9/16/2024 11:39:15 PM notice HttpServerBase Hassio authentication successful
9/16/2024 11:39:15 PM notice modbus2mqtt modbus2mqtt listening on  37e92509-modbus2mqtt: 3000
9/16/2024 11:39:15 PM notice modbuscache readDiscreteInputs TIMEOUT: slave:3 address: 3 length:1  retrying ... 
9/16/2024 11:39:15 PM notice modbuscache readHoldingRegisters slave: 3 startAddress: 117 length: 8: Data length error, expected 21 got 94
9/16/2024 11:39:16 PM notice modbuscache readInputRegisters TIMEOUT: slave:3 address: 0 length:76  retrying ... 
9/16/2024 11:39:17 PM notice modbuscache readHoldingRegisters TIMEOUT: slave:3 address: 0 length:45  retrying ... 
9/16/2024 11:39:17 PM notice modbuscache readHoldingRegisters slave: 3 startAddress: 0 length: 45: Data length error, expected 95 got 92
9/16/2024 11:39:19 PM notice modbuscache readHoldingRegisters TIMEOUT: slave:3 address: 40 length:1  retrying ... 
9/16/2024 11:39:19 PM notice modbuscache Retry successfully executed: slave:3 address: 40 length:1
9/16/2024 11:39:24 PM ERR! bus poll(3) connection failed Error: TCP Connection Timed Out
9/16/2024 11:39:24 PM notice modbuscache Retry Connect: module : TCP Connection Timed Out Error: TCP Connection Timed Out
9/16/2024 11:39:24 PM notice modbuscache     at Socket.<anonymous> (/usr/app/node_modules/modbus-serial/ports/tcpport.js:158:28)
9/16/2024 11:39:24 PM notice modbuscache     at Socket.emit (node:events:517:28)
9/16/2024 11:39:24 PM notice modbuscache     at Socket.emit (node:domain:489:12)
9/16/2024 11:39:24 PM notice modbuscache     at Socket._onTimeout (node:net:598:8)
9/16/2024 11:39:24 PM notice modbuscache     at listOnTimeout (node:internal/timers:569:17)
9/16/2024 11:39:24 PM notice modbuscache     at process.processTimers (node:internal/timers:512:7)
9/16/2024 11:39:24 PM notice modbuscache readHoldingRegisters TIMEOUT: slave:3 address: 0 length:45  retrying ... 
9/16/2024 11:39:24 PM notice modbuscache readHoldingRegisters slave: 3 startAddress: 0 length: 45: Data length error, expected 95 got 87
9/16/2024 11:39:32 PM ERR! bus poll(3) connection failed Error: TCP Connection Timed Out
9/16/2024 11:39:32 PM notice modbuscache Retry Connect: module : TCP Connection Timed Out Error: TCP Connection Timed Out
9/16/2024 11:39:32 PM notice modbuscache     at Socket.<anonymous> (/usr/app/node_modules/modbus-serial/ports/tcpport.js:158:28)
9/16/2024 11:39:32 PM notice modbuscache     at Socket.emit (node:events:517:28)
9/16/2024 11:39:32 PM notice modbuscache     at Socket.emit (node:domain:489:12)
9/16/2024 11:39:32 PM notice modbuscache     at Socket._onTimeout (node:net:598:8)
9/16/2024 11:39:32 PM notice modbuscache     at listOnTimeout (node:internal/timers:569:17)
9/16/2024 11:39:32 PM notice modbuscache     at process.processTimers (node:internal/timers:512:7)
9/16/2024 11:39:32 PM notice modbuscache readHoldingRegisters TIMEOUT: slave:3 address: 0 length:45  retrying ... 
9/16/2024 11:39:32 PM notice modbuscache readHoldingRegisters slave: 3 startAddress: 0 length: 45: Data length error, expected 95 got 88
9/16/2024 11:39:34 PM notice modbuscache readHoldingRegisters TIMEOUT: slave:3 address: 27 length:1  retrying ... 
9/16/2024 11:39:34 PM notice modbuscache Retry successfully executed: slave:3 address: 27 length:1
9/16/2024 11:39:40 PM ERR! mqttdiscover poll: MQTT client is not connected
9/16/2024 11:39:40 PM ERR! mqttdiscover poll: MQTT client is not connected
9/16/2024 11:39:40 PM ERR! mqttdiscover poll: MQTT client is not connected
/usr/app/node_modules/@modbus2mqtt/server/dist/mqttdiscover.js:429
            throw new Error('poll: MQTT client is not connected');
                  ^

Error: poll: MQTT client is not connected
    at MqttDiscover.getMqttClient (/usr/app/node_modules/@modbus2mqtt/server/dist/mqttdiscover.js:429:19)
    at /usr/app/node_modules/@modbus2mqtt/server/dist/mqttdiscover.js:525:50
    at Array.forEach (<anonymous>)
    at /usr/app/node_modules/@modbus2mqtt/server/dist/mqttdiscover.js:524:45

Node.js v18.20.3
[23:39:40] INFO: Service  exited with code 1 (by signal 0)
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service modbus2mqtt: stopping
s6-rc: info: service modbus2mqtt successfully stopped
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service base-addon-log-level: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service base-addon-log-level successfully stopped
s6-rc: info: service base-addon-banner: stopping
s6-rc: info: service base-addon-banner successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped

**Comment by albgit** [comment]
After the last update modbus2mqtt starts normally
